# Generated by Django 4.0.1 on 2022-02-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('promo', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='promo_codes', to='billing.account')),
            ],
            options={
                'db_table': 'billing_promo_code',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('reason', models.CharField(choices=[('OTHER', 'Прочее'), ('FEE', 'Абонентская плата'), ('PROMO', 'Активация промо-кода')], default='OTHER', help_text='Причина операции', max_length=5)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='billing.account')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
