# Generated by Django 4.0.1 on 2022-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='reason',
            field=models.CharField(choices=[('OTHER', 'Прочее'), ('FEE', 'Абонентская плата'), ('PROMO', 'Активация промо-кода'), ('HELLO', 'Приветственный бонус')], default='OTHER', help_text='Причина операции', max_length=5),
        ),
    ]
